### ISSUE TITLE
Phase 1 Tests: Possible to pass check & checkmate with incorrect code

### ISSUE THREAD

**Issue by frozenfrank** [softwareconstruction240/softwareconstruction#61]
## Description
While the Check and Checkmate do test certain scenarios, they don't seem to actually exercise the full range of Chess possibilities to ensure that the student code is _correct_. Certain beginner mistakes made in the code can lead to code that still passes the tests even though they wouldn't fly in actual tournament play. 

An effort is made in this issue to point out some of the mistakes that can be made, and to provide additional test cases which would validate that the student algorithms are actually correct. Verifying and more thoroughly exploring the results contained in this issue would be one of the first steps forward from here.

### Personal Experience
As I reviewed my code for Phase 1, I discovered that as I checked for `validMoves`, I only called `pieceMoves` on each of the opponents pieces. I passed the tests. However, this could potentially lead to the opponent moving a piece to block my piece from checking the king **that simultaneously exposes their king to check from a different direction.** I don't believe this case was tested properly.

### Student Reports
According to one student:
> Just a heads up for everyone the simple IsInCheckmate tests (not the full game one) can still pass even if your function is wrong.  I had a bug in mine where it didn't correctly reset the board to the original after each iteration, causing it to only try the first 2 moves and not any of the others.  I only noticed it was wrong because I had it set up to catch the exception from makeMove
> ...Yeah I fixed it, you have to be really careful to change the board back to the original after you make moves to test.  I thought I was setting it back but I wasn't.

## Proposed Test Cases
1. Verify that the board is being reset. A test case where the only valid move to save the current team from check would usually require attempting multiple iterations of valid moves. Create a case where, if the board is not reset properly, then subsequent pieces would produce incorrect moves and fail the test. 
    - One idea could be one where _two_ different pieces could save the king from check. If the first piece saves the king (but is not reset), then the second piece would provide more valid moves than should be permitted.
2. Block incoming check without exposing king to another threat. A test case where one enemy piece is threatening the king, and a friendly piece is currently blocking the king from check in a different direction.
3. A double check position. Consider [this setup](https://boardgames.stackexchange.com/q/45537) which should be considered _checkmate_ if it's black's turn. (I'm not sure if this would cover either of the holes I suggested above, but it does seem like a useful test.)

## Therefore, What?
Well, I could be wrong, and the test cases could be totally comprehensive already. Some external perspective to verify that the test cases are considering all the perspectives would be good. I'm just reporting the information I have available so far.

**Comment by frozenfrank** [comment]
@19mdavenport What do you know about the current Phase 1 check & checkmate tests? How comprehensive are they?

**Comment by 19mdavenport** [comment]
Currently isInCheckmate could be reduced to isInCheck or isInStalemate. I was aware of the possible isInCheck reduction last semester, but I thought that the phase 3 and 6 tests needed more attention, so I spent the time I had for enhancing test cases last semester on those.

**Comment by aonstott** [comment]
I was the student who posted about the issue on slack, here's specifically what happened:  I had my isInCheckmate function set up to save a clone of the original board, and then try all the moves for every piece of the team being checked with the function.  I iterated through all the valid moves for each piece to see if any got the king out of check, each time changing the board back to the cloned original board before trying the next move.  

I had a bug causing the board to only reset to the original after trying the first move.  Which led to most of the potential moves never being tried.  For the WhiteTeamCheckmate() test, my function only tried the first 2 moves the king could try to get out of checkmate, but still returned true since it could not find an option to get out of checkmate.  So basically, if there had been a move the king could have taken which was not checked until the 4th or 5th iteration, my function would not have caught it.  

I think adding a test or 2 where the king is in check, and only has 1 possible move to get out of check may help?  As far as I can tell, the tests don't include any cases to test isInCheckmate() where the King is currently in check but can still escape or be protected by another piece.

**Comment by frozenfrank** [comment]
Resolved by #107.
