### ISSUE TITLE
Update All Communication Links to Reference A Bitly Link

### ISSUE THREAD

**Issue by frozenfrank** [softwareconstruction240/softwareconstruction#91]
## Overview
We'll want to use a TA controlled account to create the bit.ly link so that we can modify the link in the future. Currently, the bit.ly link will point at the current Slack channel sign-up link, but we'll have the flexibility to easily change this to a different Slack channel or even a Discord channel in the future. 

**Going forward, only this link should be published as the source for joining any communication channel.**

## Link Sources
This will require searching for old links in all of the following places:
* Canvas Course
* Canvas Blueprint course pages
* Instruction Pages
* [Email Templates](https://docs.google.com/document/d/1UNPesigagvfbHJ97NnAX1gFuNtrpBEjIXgce4e0sIHQ/edit#heading=h.levve1gpuveq)

## Other Shortcut Links
We should consider creating shortcut links for other related documents at the same time as this issue. Candidates include:
* [TA Schedule](https://docs.google.com/document/d/12ZrcsQAfVirCuCwzI0TKX_tSPyBOjqB9vDE-sx1n_S0/edit?usp=sharing)
* [Help Queue](https://help.cs240.click)

**Comment by leesjensen** [comment]
Perhaps we could solve this a different way. This came up because we keep creating a new slack server very semester. As an alternative, how about we just keep the same server. We should also create a single location where the link is found so that it is trivial to update.

I couldn't find anything in GitHub that pointed to the the TA schedule doc and so there is nothing to update there.

The TA schedule doc doesn't have a reference. So we don't need to worry about that.

Canvas has the following links for getting help:

Main bar
<img width="1131" alt="image" src="https://github.com/user-attachments/assets/c81b1e10-e283-42d9-87e9-65269167c5f0" />

Help Central
<img width="1080" alt="image" src="https://github.com/user-attachments/assets/3f59870e-6910-4fd0-b0df-bed05aff2bd5" />

<img width="1090" alt="image" src="https://github.com/user-attachments/assets/c230217a-4d5f-4feb-8dea-57a09c472f6a" />

So I changed the "Get Help from Others" Canvas info. It was already outdated with a reference to "discussions" that are available in the videos. The access your textbooks link was broken and so I removed that.

Main bar
<img width="1115" alt="image" src="https://github.com/user-attachments/assets/b069b3c0-f4a6-4393-b077-8abf5859b01d" />

Getting help
<img width="1086" alt="image" src="https://github.com/user-attachments/assets/0ec5ce1f-4346-4b73-98be-878a24d80ca2" />


I then removed the main bar links. This only leaves a single place that needs to be updated each semester. If we decide to stop creating a new server every semester that will remove the need for an update entirely.
